import type { GuideContent } from "../types"

export const guideEn: GuideContent = {
  basics: {
    title: "Getting started: accounts and sign-in",
    summary: "Your first visit, trying demo accounts, and signing out.",
    before: "Have the email and password provided by your administrator ready. Contact HR if you need an account; there is no self-registration page.",
    steps: [
      "Open the HRFlow website and select Sign in. Use TH or EN at the top to change the language if needed.",
      "Enter your account email in Email and your password in Password. Check for accidental spaces.",
      "To check the password, select the eye icon inside its field. Select it again to hide the password before continuing.",
      "To try the demo, expand Explore with a demo account and choose a role. This fills the fields; it does not sign you in yet.",
      "Select Sign in once and wait for the pending button to finish. You normally reach Dashboard, or the page you selected before signing in.",
      "Look at the available menus. Different roles see different pages; a colleague having more menus does not mean your account is broken.",
      "When finishing on a shared computer, open the account avatar at the top right, select Sign out, and confirm in the dialog.",
    ],
    result: "You can open the workspace allowed for your account and sign out when finished.",
    tips: ["Forgotten password: contact HR or an administrator; self-service password reset is not available.", "Incorrect credentials: check the email, keyboard language, and Caps Lock before retrying.", "Demo accounts contain demonstration data, not your organisation's real employee accounts."],
  },
  navigation: {
    title: "Find pages, change language, and use mobile",
    summary: "Understand the main controls and find tasks without remembering menu positions.",
    before: "Sign in first. Your role determines which menus are available.",
    steps: [
      "On a computer, select a page in the left sidebar, such as Attendance or Leave. The highlighted item is the current page.",
      "On mobile, open navigation using the top-left menu button, then choose a page. The menu closes after your selection.",
      "If you cannot find a menu, select the magnifying glass or Find a page, type the task name, and choose a result. Results include only pages your role can use.",
      "Select TH to switch to Thai or EN to switch to English. The button names the language it will switch to, not the current language.",
      "Use the sun or moon button to switch between light and dark themes. The app remembers language and theme choices.",
      "If a table is wider than the screen, scroll sideways inside its frame. Scroll vertically to read the rest of the page.",
      "When Loading... appears, wait for that section. You can still choose another page without repeatedly clicking. Keyboard users can use Tab to move, Enter to activate, and Escape to dismiss a dialog.",
    ],
    result: "You can find a page and adapt the interface to your device.",
    tips: ["Names, departments, and user-entered text keep their stored wording when you change language.", "Return to this page through User guide in the menu or search for guide."],
  },
  dashboard: {
    title: "Read the dashboard and start your day",
    summary: "Use task shortcuts and understand whose information the totals describe.",
    before: "Know your role: Employee, Manager, HR Manager, or Administrator.",
    steps: [
      "Open Dashboard from the sidebar or mobile menu.",
      "Under Start your day, choose a shortcut such as attendance, leave, or payslips from the options available to you.",
      "Employees see their own check-in and check-out times, leave balances, and latest payslip period.",
      "Managers see team size, attendance, and pending approvals. Open Attendance or Leave for details.",
      "HR and administrators see company totals, attendance, pending work, and payroll figures. Open the underlying list before making a decision.",
      "Charts and data cards may arrive after the shortcuts. Wait for loading to finish; an empty message can mean there are no records for that period.",
    ],
    result: "You know where to start and can distinguish personal, team, and company information.",
    tips: ["A missing employee profile message means the account may not be linked to an employee. Ask HR to check.", "Payroll calculations and figures in this project are for demonstration."],
  },
  glossary: {
    title: "Common terms and statuses",
    summary: "Plain explanations for people new to HR work or online systems.",
    before: "Use this topic as a reference while reading the screens. You do not need to memorise everything.",
    steps: [
      "Dashboard means the overview page. A profile is an employee's record page.",
      "Pending Manager and Pending HR mean a leave request has not completed approval. Another review step is still needed.",
      "Approved means accepted, Rejected means declined, and Cancelled means the requester withdrew a pending request.",
      "A payroll run is the calculation for one month and year. It progresses from Calculated to Reviewed, Approved, and Paid.",
      "Gross income is the amount before deductions. Deductions are amounts taken away. Net pay is the resulting amount shown on the payslip.",
      "CSV is a table file you can open in Excel. PDF is a document you can save from the browser's print dialog.",
      "Permissions define what an account can do. For example, managing a team does not automatically grant access to that team's salaries.",
    ],
    result: "You can understand key labels and statuses and recognise the next step.",
    tips: ["Read status text as well as its colour; colour alone should not determine whether a task is complete."],
  },
  profile: {
    title: "View your profile and request corrections",
    summary: "Check your personal, employment, and contact information.",
    before: "Your account needs a linked employee profile. If My profile returns to Dashboard, contact HR.",
    steps: [
      "Open the account avatar at the top right and select My profile.",
      "Check your name, employee code, department, position, and manager to confirm that this is your record.",
      "Read the contact, address, emergency contact, and other sections available for your role.",
      "If you are an employee or manager and find an error, note the field and correct value, then contact HR or an administrator. These roles cannot edit their own record here.",
      "HR and administrators can select Edit and follow the editing topic. Check the saved profile again afterwards.",
    ],
    result: "You can confirm your record and know who can correct it.",
    tips: ["Do not share your password with someone correcting a record. Identify the employee code and field instead."],
  },
  attendance: {
    title: "Check in, check out, and view history",
    summary: "Record working times on desktop or mobile and confirm that they were saved.",
    before: "Use your own account linked to an employee and an internet connection. Respond to location permission prompts according to your organisation's process.",
    steps: [
      "Open Attendance. If tabs are shown, select My attendance.",
      "At the start of work, check that no check-in time is recorded for today, then select the green Check in button once.",
      "If the browser asks for location access, respond and wait for the success message. The app may briefly wait for location before sending the record.",
      "Confirm that a check-in time appears and Check in is disabled. The status may be Present or Late according to the attendance rules.",
      "At the end of work, return here and select Check out once. You must check in before checking out.",
      "Wait for success and confirm the check-out time. Review My history below, which shows up to 30 recent records.",
      "Use the monthly summary cards to review present, late, absent, and leave counts. If a date or time is wrong, note the details and contact HR.",
    ],
    result: "Today's check-in and check-out are recorded and can be reviewed in history.",
    tips: ["Disabled button: check whether the action has already been completed or is still being saved.", "This screen has no control for correcting past times. Ask HR for help with mistakes.", "The app can submit without coordinates if location access is declined, but follow your organisation's attendance process."],
  },
  leaveRequest: {
    title: "Submit a new leave request",
    summary: "Choose the type, dates, and reason, then check who needs to review it.",
    before: "Prepare your dates and reason and check the relevant leave balance. Your account must have an employee profile.",
    steps: [
      "Open Leave. If tabs are available, use My requests to check existing requests and balances first.",
      "Select New request to open the form, then choose a leave type from the list.",
      "Select the start and end dates. For one day, use the same date in both fields. The end cannot precede the start.",
      "Enter a clear reason of at least five characters, such as planned annual leave discussed with your manager.",
      "Review the entries. The app counts Monday to Friday including both endpoints. It does not deduct company holidays and has no half-day option.",
      "Submit once. If a message reports an insufficient balance or invalid dates, correct the entries before trying again.",
      "After success, find the new request in the list. It starts with Pending Manager when a manager is assigned, otherwise Pending HR.",
      "Track the status on Leave. Successfully submitting a request does not mean leave has been approved.",
    ],
    result: "The list contains your request with its dates, day count, and pending status.",
    tips: ["The current form has no attachment upload field. Ask HR where to send supporting documents.", "Split requests crossing calendar years and check with HR; balance checks use the start date's year.", "Check existing requests before submitting to avoid duplicate or overlapping entries."],
  },
  leaveTracking: {
    title: "Track or cancel a leave request",
    summary: "Read approval progress and withdraw requests still waiting for review.",
    before: "You need an existing request of your own. Cancellation is available only while waiting for a manager or HR.",
    steps: [
      "Open Leave and choose My requests if your account also has an approvals tab.",
      "Find the type and date range, then select View or the row to open details.",
      "Read the status and approval timeline, including reviewers, comments, and decision times.",
      "If you no longer need the leave and it is still pending, select the cancellation action in the details and check the success message.",
      "Check the updated list. To change dates on a pending request, cancel it first, then submit a new request with the correct details.",
      "Approved or rejected requests cannot be cancelled using the pending-request control. Contact HR for the next steps.",
    ],
    result: "You know the current review step; a successfully withdrawn request is marked Cancelled.",
    tips: ["Pending HR after manager approval is normal; final confirmation is still required.", "The balance updates on final approval, not immediately on submission."],
  },
  payslips: {
    title: "View payslips and save a PDF",
    summary: "Check your income and deductions and print an issued document.",
    before: "You need an employee profile and an issued payslip. If none appear, ask HR whether the run has been marked Paid.",
    steps: [
      "Open My Payslips. Managers whose sidebar lacks this menu can use Open work page in this guide topic to open their own payslips.",
      "Find the required month and year, check the net amount, and select View on that row.",
      "Check the employee name, code, and pay period before reading the figures.",
      "Review income, deductions, and net pay. If something seems wrong, tell HR the period and the line you want checked.",
      "Select Print to open the browser's print dialog. Choose a printer or Save as PDF.",
      "Check the preview and print or save the document. Choose a recognisable file name and folder.",
    ],
    result: "You can view your payslip and, if needed, keep a printed copy or PDF.",
    tips: ["Managers do not automatically have access to their team's payslips.", "This project uses demonstration calculations. Have HR check them before real use."],
  },
  tax: {
    title: "View an annual tax summary",
    summary: "Open totals from paid runs and print the demonstration document.",
    before: "You need an employee profile. This is a sample document, not a verified tax certificate.",
    steps: [
      "Open My Payslips and select the annual tax document button above the list.",
      "Check the employee name and year in the heading. The current year opens by default.",
      "Read the income, withholding, and social security totals from paid runs in that year.",
      "If the year is wrong or records are missing, contact HR. This page currently has no year-selection field.",
      "Select Print, then print or save a PDF in the browser. Check the document with HR before relying on it.",
    ],
    result: "You can read the displayed year's totals and save a sample document.",
    tips: ["Zero totals may mean no paid runs exist for that year, not that the employee record is missing."],
  },
  teamAttendance: {
    title: "Review team attendance",
    summary: "For managers, HR, and administrators reviewing today's status within their scope.",
    before: "Managers need an employee profile with assigned direct reports.",
    steps: [
      "Open Attendance and select Team attendance. Accounts without a personal profile may see the team section directly.",
      "Read the section heading. Managers see direct reports; HR and administrators see the first 20 company employees in this card.",
      "Check each name and employee code alongside its status. Do not treat the first 20 names as a full company summary.",
      "If someone is missing from the team, ask HR to check their assigned manager.",
      "Contact HR about incorrect records. This card is for viewing status and has no time-editing controls.",
    ],
    result: "You can review today's team status while understanding the limits of the displayed list.",
    tips: ["HR and administrators can also use Reports to review attendance for a chosen date range."],
  },
  employeeSearch: {
    title: "Find an employee and open their profile",
    summary: "Use names, codes, email addresses, and filters to find records faster.",
    before: "HR and administrators see everyone; managers see direct reports. Employees use their own profile page.",
    steps: [
      "Open Employees and enter a first name, last name, email, or employee code in Search.",
      "Pause briefly after typing or press Enter to search immediately. You do not need to submit after every character.",
      "If there are too many results, select a department or employment status to narrow the list.",
      "Confirm the code and department, then select the name to open the profile. Use Previous and Next below the list for other result pages.",
      "If nothing matches, select Clear filters and try again. Managers should ask HR to check team assignments if someone is still missing.",
    ],
    result: "You can open the correct employee record within your access scope.",
    tips: ["Scroll tables sideways on mobile to see additional columns and row actions.", "Some management controls may be visible, but saving still requires HR or administrator permissions. Managers should use employee records for reviewing their team."],
  },
  employeeCreate: {
    title: "Add a new employee record",
    summary: "Complete required information and check the record after saving.",
    before: "Prepare the employee code, email, department, position, start date, and salary. Only HR and administrators can create records.",
    steps: [
      "Open Employees and select Add employee.",
      "Under basic details, enter an employee code of at least two characters, first name, last name, and valid email. Add a phone number if available.",
      "Choose a department and position from the available lists. If a required option is missing, contact the administrator; this form does not create departments or positions.",
      "Under employment details, select the employment type, status, start date, and a salary greater than zero.",
      "Select a manager when applicable. This affects team membership and the manager step in leave requests.",
      "Add available optional details such as address, emergency contact, bank information, and relevant identification numbers. Check sensitive entries against the original documents.",
      "Use the form section links to review each part, then select Create employee in the save bar.",
      "If saving fails, read field messages or the error summary. Correct issues such as a duplicate code or email before submitting again.",
      "After success, search for the new code and open the profile to verify it. Creating an employee record does not automatically create a login account; account setup and linking are separate administrator tasks.",
    ],
    result: "The list contains a new employee record with checked employment information.",
    tips: ["Prepare missing required information rather than inventing bank or personal details to pass validation.", "There is no login-account management screen in this app; contact the project administrator."],
  },
  employeeEdit: {
    title: "Edit an employee or change their status",
    summary: "Update records and handle termination after confirming the person's identity.",
    before: "Use an HR or administrator account and prepare verified replacement information.",
    steps: [
      "Find the employee by code or name, open their profile, and confirm the person before changing anything.",
      "Select Edit employee from the profile or the row's actions menu.",
      "Go to the relevant section and change the values. Save becomes available when the form has actually changed.",
      "Save changes, then verify the values on the profile. To discard edits, use Cancel before submitting.",
      "For termination, open the row's actions menu and choose Deactivate. Read the employee name in the confirmation and proceed only when certain.",
      "Confirm the Terminated status. The record remains in the system; you may need a different status filter to find it.",
    ],
    result: "The selected person's information or employment status is updated, with an audit record for review.",
    tips: ["Termination does not delete the profile. Do not assume it also disables the login account; verify account access separately with the administrator.", "If an edit is wrong, ask HR or the administrator to correct the existing record rather than creating a duplicate."],
  },
  leaveApprovals: {
    title: "Review team and HR leave approvals",
    summary: "Read the request before deciding and understand the manager and HR review steps.",
    before: "Managers review their team's manager step, HR reviews the HR step, and administrators can handle either step.",
    steps: [
      "Open Leave and choose Approvals. Check the number of pending items.",
      "Find the request, confirm the employee, leave type, and dates, then select View.",
      "Read the reason, day count, and approval timeline. Contact the requester before deciding if information is unclear.",
      "Enter a comment where provided, such as the reason for rejection, so the requester understands the decision.",
      "Select Approve or Reject to match your decision. This records a real action, so check the details before selecting it.",
      "Wait for success and check the updated queue or status. Manager approval moves a request to Pending HR; HR approval completes it.",
      "If the app says it was already decided, reopen the current record. Another authorised person may have handled it.",
    ],
    result: "The request has a recorded decision and comment that the requester can follow.",
    tips: ["Missing decision controls: check your role and the request's current review step.", "An empty queue means nothing currently awaits you, not necessarily that the team has no leave requests."],
  },
  payrollCreate: {
    title: "Generate and inspect a payroll run",
    summary: "Start a monthly run and review employees and figures before approval.",
    before: "Use an HR or administrator account. Check employee, salary, attendance, and leave records first. Calculations remain demonstrations.",
    steps: [
      "Open Payroll and check whether the month and year already exist before creating another run.",
      "Select Generate payroll, choose the correct month and year, and submit once.",
      "Wait for calculation to finish. If the app reports that the run exists, open the existing one instead of repeatedly submitting.",
      "Select the month in the list. Check employee count, status, creator, and gross, deduction, and net totals.",
      "Review each employee row and open its payslip to inspect the components. Read the adjustment topic before adding individual income or deductions.",
      "Do not confirm payment until review and approval are complete. Compare the generated figures with HR's supporting records first.",
    ],
    result: "A Calculated run is available with employee items ready for review.",
    tips: ["Generating a run can take longer than opening a page because it calculates multiple employees. Wait for the result before retrying.", "This button does not delete or regenerate an existing run. Contact the administrator if the wrong period was created."],
  },
  payrollAdjust: {
    title: "Add payroll income or deductions",
    summary: "Add an individual employee's adjustment and verify the resulting totals.",
    before: "Prepare the label, type, positive amount, and reason. Complete and review adjustments before approval or payment.",
    steps: [
      "Open Payroll and choose the correct month and year.",
      "Find the employee row, verify the name and code, then select Adjust.",
      "Choose Income or Deduction and enter a clear label for the item.",
      "Enter a positive amount and an optional note. Check decimal places and the number of digits before saving.",
      "Add the adjustment and wait for success. Check the row totals and open the payslip to confirm the added line.",
      "If an adjustment is wrong, pause approval and contact the administrator. There are no controls for deleting or editing an existing adjustment; do not add compensating entries without checking the totals.",
    ],
    result: "The chosen employee has an additional line and updated income, deductions, and net pay.",
    tips: ["Check the run status before adjusting it. A visible button is not a reason to change an approved or paid run without an agreed HR process."],
  },
  payrollApprove: {
    title: "Review, approve, and record payment",
    summary: "Follow the run's stages and distinguish a payment record from an actual bank transfer.",
    before: "Use HR or administrator access and complete the required review. The available button depends on the run's current status.",
    steps: [
      "Open the run and make a final check of its month, year, employee count, and net total.",
      "For a Calculated run, complete the review and select Mark reviewed. Confirm that the status becomes Reviewed.",
      "When ready, select Approve and verify the approver and Approved status.",
      "Arrange the actual payment through your organisation's process outside HRFlow. The website does not transfer money to bank accounts.",
      "After checking evidence of actual payment, select Mark as paid, read the confirmation, and confirm.",
      "Verify Paid status and the payment date. This step issues payslips in the system. Use Export CSV on the run if you need its table file.",
      "If the status is unexpected or already advanced, reopen the current record. Do not approve or mark paid repeatedly; contact the administrator about mistakes.",
    ],
    result: "The run progresses to Paid and employees can see their issued payslips.",
    tips: ["There is no rollback button for run statuses. Verify the period and amounts before confirmation.", "Payroll and tax formulas are examples and require review before real use."],
  },
  reports: {
    title: "Download reports for Excel",
    summary: "Choose the report, set dates where available, and download CSV.",
    before: "Use HR or administrator access and decide which report you need.",
    steps: [
      "Open Reports and choose the employee, attendance, leave, or payroll report card.",
      "Attendance and leave reports have From and To fields. Choose your date range with the start on or before the end.",
      "Employee and payroll report cards have their own export buttons and no date-range controls.",
      "Select Export CSV, wait for the download, and check the file in your browser's downloads.",
      "Open it in Excel or another spreadsheet app. Check column headings, dates, and a few sample rows before sharing.",
      "If Thai text appears corrupted, import through Excel's Text/CSV import and choose UTF-8 encoding. If there are no rows, check the dates and source records.",
    ],
    result: "You have a table file for the selected report ready for review.",
    tips: ["Reports may contain employee and salary information. Share them only with the appropriate people."],
  },
  audit: {
    title: "Review the audit log",
    summary: "Find who performed an important action, when it happened, and its recorded details.",
    before: "Use HR or administrator access and know the approximate time and action you are investigating.",
    steps: [
      "Open Audit Log from the menu.",
      "Read the time, actor, action, and entity columns to find relevant events.",
      "Use the pagination controls for other records. Each page shows up to 20 entries.",
      "If a row has View in its details column, expand it. Some details are field names or record identifiers for the administrator to investigate.",
      "When requesting help, provide the time, actor, and event name. This page reviews history; it does not undo actions.",
    ],
    result: "You can identify an event and provide useful information for follow-up.",
    tips: ["The log records supported important actions, not every click or page visit."],
  },
  attendanceSettings: {
    title: "Set working hours and attendance rules",
    summary: "Administrator instructions for values used when evaluating attendance.",
    before: "Agree start and end times and the grace period with HR before making changes.",
    steps: [
      "Open Settings and select Attendance rules.",
      "Note the current values, then set the work start and end times using the format accepted by the fields.",
      "Enter the late-arrival grace period in minutes. It works with the start time to determine late status.",
      "Enter standard daily working hours within the permitted range and review every field.",
      "Select Save attendance rules after making a change. Wait for success; Save becomes disabled again until another edit is made.",
      "Verify the saved values and inform HR. Saving these rules does not automatically recalculate or correct every past attendance record.",
    ],
    result: "New attendance settings are stored for operations that use those rules.",
    tips: ["If saving fails, follow the field messages about time format or permitted numeric ranges before submitting again."],
  },
  payrollSettings: {
    title: "Set payroll calculation values",
    summary: "Update demonstration rates and divisors while checking the units used by each field.",
    before: "Have the responsible person verify the formulas and rates first. Administrators can edit them; sample values are not tax or legal advice.",
    steps: [
      "Open Settings and select Payroll rules.",
      "Note current values and read the field hints, especially rates entered as fractions: for example, 0.05 represents 5%.",
      "Set the social security rate and maximum base to the values verified by the responsible person.",
      "Set the demonstration withholding rate, late deduction per minute, and the divisor for absence deductions.",
      "Check all units and numbers, then select Save payroll rules. Wait for success and verify the displayed values.",
      "Inform HR before generating the next run. Updating defaults does not retroactively change amounts in existing runs.",
    ],
    result: "New defaults are stored for calculations that subsequently use these rules.",
    tips: ["If unsure about a rate or formula, stop and ask the responsible person. Do not copy sample values straight into real payroll."],
  },
  troubleshooting: {
    title: "What to check when something goes wrong",
    summary: "Distinguish form, permission, account, and connection issues before asking for help.",
    before: "Note the page, time, and message without sharing your password.",
    steps: [
      "Dimmed Save button: check whether anything has changed and whether a save is still pending. Correct any field validation messages first.",
      "Missing menu or access denied: check that you signed into the right account and role. Ask HR or an administrator to review access if needed.",
      "No employee profile, no attendance controls, or My profile returning to Dashboard: ask the administrator to check the account's employee link.",
      "Empty table: clear search and filters, check dates or status, and wait for loading to finish before assuming records are missing.",
      "Long loading time: check your connection and wait briefly. You can still change menus. If a save is pending, do not submit again until you have checked whether it completed.",
      "If the problem continues, contact HR or the administrator with the page, steps taken, time, and exact error. Hide unnecessary personal information in any screenshot you share.",
      "After the issue is resolved, check the latest records before continuing, such as whether a leave request was already submitted, to avoid duplicates.",
    ],
    result: "You can make basic checks and give the administrator useful details.",
    tips: ["The guide explains actions; it does not grant permissions, change records, or perform tasks for you.", "Button labels follow the selected language. Use the top bar to switch between Thai and English."],
  },
}
